version: "3.8"

services:
  video-processor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads
      - outputs_data:/app/outputs
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=524288000
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - PORT=5000
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  uploads_data:
  outputs_data:
