version: "3.8"

networks:
  video_network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - video_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  video-processor-api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - video_network
    volumes:
      - video_data:/data
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=524288000
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - PORT=5000
      - DEBUG=false
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=8
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  video-processor-worker:
    build: .
    networks:
      - video_network
    volumes:
      - video_data:/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
      - WORKER_MODE=celery
      - CELERY_CONCURRENCY=3
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

volumes:
  redis_data:
  video_data:
