networks:
  video_network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - video_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  video-processor-api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - video_network
    volumes:
      - uploads_data:/data/uploads
      - outputs_data:/data/outputs
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - DEBUG=false
      - PORT=5000
      - MAX_CONTENT_LENGTH=524288000
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=8
      - GUNICORN_TIMEOUT=600
      - GUNICORN_MAX_REQUESTS=500
      - GUNICORN_MAX_REQUESTS_JITTER=50
      - FLASK_CORS_ORIGINS=https://ooc4wcggkoowkws8kkks0cgo.coolify.khaledalnassan.com
      # For Coolify: REDIS_URL=redis://default:YOUR_PASSWORD@redis-database-xxx:6379/0
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  video-processor-worker:
    build: .
    networks:
      - video_network
    volumes:
      - uploads_data:/data/uploads
      - outputs_data:/data/outputs
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - WORKER_MODE=celery
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
      - CELERY_CONCURRENCY=3
      - CELERY_PREFETCH_MULTIPLIER=1
      - REDIS_URL=redis://redis:6379/0
      # GPU support (ignored if no GPU available)
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    stop_grace_period: 120s
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
    # GPU device request (Compose v2) - requires Docker Compose v2.3+
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  redis_data:
  uploads_data:
  outputs_data:
