version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  video-processor-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - video_data:/data
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=524288000
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - PORT=5000
      - DEBUG=false
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:5000",
        "--workers",
        "2",
        "--timeout",
        "300",
        "app:app",
      ]

  video-processor-worker:
    build: .
    volumes:
      - video_data:/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
     command:
       [
         "celery",
         "-A",
         "app.celery",
         "worker",
         "--loglevel=info",
         "--concurrency=4",
         "--prefetch-multiplier=1",
         "--optimization=speed",
       ]

volumes:
  redis_data:
  video_data:
