version: "3.8"

services:
  video-processor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - video_data:/data
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=524288000
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - PORT=5000
      - DEBUG=false
      - UPLOAD_FOLDER=/data/uploads
      - OUTPUT_FOLDER=/data/outputs
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

volumes:
  video_data:
